export const images = {
    "Pre Wedding": ["1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL"],
    "Wedding": ["1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL"],
    "Maternity Shoot": ["1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL"],
    "Post Wedding": ["1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL"],
    "Baby Shoot": ["1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL"],
    "Birthday Shoot": ["1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL",
        "1EpMqCH9rYHDbHgGv-QkY4xom2LVbGpRL"],
}
